import Link from "next/link";
import Navbar from "@/components/Navbar";
import { Plane, MapPin, Brain, Zap, Shield, Globe } from "lucide-react";

export default function Home() {
  return (
    <>
      <Navbar />
      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-transparent to-accent/5" />
        <div className="relative mx-auto max-w-7xl px-4 py-24 sm:px-6 sm:py-32 lg:py-40">
          <div className="text-center">
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-4 py-1.5 text-sm font-medium text-primary">
              <Brain className="h-4 w-4" />
              Powered by Google Gemini &amp; RAG
            </div>
            <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl lg:text-6xl">
              Plan Your Perfect Trip
              <br />
              <span className="text-primary">with AI Intelligence</span>
            </h1>
            <p className="mx-auto mt-6 max-w-2xl text-lg text-muted">
              Get personalized, day-by-day itineraries generated by AI. Real hotels,
              flights, activities, and local tips — all tailored to your preferences.
            </p>
            <div className="mt-10 flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
              <Link
                href="/register"
                className="inline-flex h-12 items-center gap-2 rounded-xl bg-primary px-8 text-base font-semibold text-white shadow-lg shadow-primary/25 transition-all hover:bg-primary-dark hover:shadow-xl hover:shadow-primary/30"
              >
                <Plane className="h-5 w-5" />
                Start Planning — Free
              </Link>
              <Link
                href="/login"
                className="inline-flex h-12 items-center rounded-xl border border-border px-8 text-base font-semibold transition-colors hover:bg-card"
              >
                Sign In
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="border-t border-border bg-card py-20">
        <div className="mx-auto max-w-7xl px-4 sm:px-6">
          <h2 className="text-center text-3xl font-bold">How It Works</h2>
          <p className="mx-auto mt-3 max-w-xl text-center text-muted">
            Three simple steps to your dream itinerary
          </p>
          <div className="mt-14 grid gap-8 sm:grid-cols-3">
            {[
              {
                icon: MapPin,
                title: "1. Set Preferences",
                desc: "Tell us your destination, dates, budget, interests, and travel style.",
              },
              {
                icon: Brain,
                title: "2. AI Generates",
                desc: "Gemini + RAG builds a complete itinerary grounded in real travel knowledge.",
              },
              {
                icon: Zap,
                title: "3. Explore & Book",
                desc: "Browse day-by-day plans with hotels, flights, activities, and local tips.",
              },
            ].map((f) => (
              <div
                key={f.title}
                className="rounded-2xl border border-border bg-background p-8 text-center transition-shadow hover:shadow-lg"
              >
                <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-xl bg-primary/10 text-primary">
                  <f.icon className="h-7 w-7" />
                </div>
                <h3 className="mt-5 text-lg font-semibold">{f.title}</h3>
                <p className="mt-2 text-sm text-muted">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Tech Stack */}
      <section className="border-t border-border py-20">
        <div className="mx-auto max-w-7xl px-4 sm:px-6">
          <h2 className="text-center text-3xl font-bold">Enterprise-Grade Stack</h2>
          <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {[
              { icon: Brain, label: "Google Gemini", desc: "Advanced LLM for itinerary generation" },
              { icon: Globe, label: "RAG Pipeline", desc: "LangChain + Pinecone for grounded responses" },
              { icon: Zap, label: "Real-Time Data", desc: "Amadeus flights & hotel APIs" },
              { icon: Shield, label: "Secure Auth", desc: "JWT + Google OAuth 2.0" },
              { icon: MapPin, label: "Google Maps", desc: "Route visualization & place details" },
              { icon: Plane, label: "Full-Stack", desc: "Next.js + NestJS + PostgreSQL + Redis" },
            ].map((t) => (
              <div
                key={t.label}
                className="flex items-start gap-4 rounded-xl border border-border p-5 transition-colors hover:bg-card"
              >
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
                  <t.icon className="h-5 w-5" />
                </div>
                <div>
                  <h3 className="font-semibold">{t.label}</h3>
                  <p className="mt-1 text-sm text-muted">{t.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border bg-card py-8">
        <div className="mx-auto max-w-7xl px-4 text-center text-sm text-muted sm:px-6">
          &copy; {new Date().getFullYear()} AI Trip Planner by Vishal N. — Built with Next.js, NestJS, Gemini &amp; RAG.
        </div>
      </footer>
    </>
  );
}
